USE [master]
GO

/****** Object:  Database [PhoneBook]    Script Date: 11/6/2015 12:29:59 PM ******/
CREATE DATABASE [PhoneBook]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PhoneBook', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\PhoneBook.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PhoneBook_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\PhoneBook_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PhoneBook] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PhoneBook].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PhoneBook] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PhoneBook] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PhoneBook] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PhoneBook] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PhoneBook] SET ARITHABORT OFF 
GO

ALTER DATABASE [PhoneBook] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PhoneBook] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [PhoneBook] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PhoneBook] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PhoneBook] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PhoneBook] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PhoneBook] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PhoneBook] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PhoneBook] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PhoneBook] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PhoneBook] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PhoneBook] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PhoneBook] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PhoneBook] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PhoneBook] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PhoneBook] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PhoneBook] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PhoneBook] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PhoneBook] SET RECOVERY FULL 
GO

ALTER DATABASE [PhoneBook] SET  MULTI_USER 
GO

ALTER DATABASE [PhoneBook] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PhoneBook] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PhoneBook] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PhoneBook] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PhoneBook] SET  READ_WRITE 
GO

